// @ts-nocheck
// HiddenInput.js
import React from "react";

export const HiddenInput = (props: any) => {
  return <input type="hidden" {...props} />;
};

export const Autocomplete = (props: any) => {
  return <input type="text" placeholder="Autocomplete field" {...props} />;
};

export const intial_Form = [
  // {
  //   id: "E9276B53-27CE-4090-A013-C0675854EC52",
  //   element: "Header",
  //   text: "Header",
  //   static: true,
  //   required: true,
  //   bold: false,
  //   italic: false,
  //   content: "Contact form ",
  //   canHavePageBreakBefore: true,
  //   canHaveAlternateForm: true,
  //   canHaveDisplayHorizontal: true,
  //   canHaveOptionCorrect: true,
  //   canHaveOptionValue: true,
  //   canPopulateFromApi: true,
  //   dirty: false,
  // },
  {
    id: "69164C85-80EE-4015-8E4B-8F7F6CEA2F1F",
    element: "TextInput",
    text: "Text Input",
    static: true,
    required: true,
    canHaveAnswer: true,
    content: "First name ",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: true,
    canHaveOptionCorrect: true,
    canHaveOptionValue: true,
    canPopulateFromApi: true,
    field_name: "text_input_F6C3B60D-A45F-4A00-9F79-C46CBE4A083E",
    label: "First name ",
    dirty: false,
  },
  {
    id: "B167181E-4E1C-4928-B218-5E2E41B7729B",
    element: "TextInput",
    text: "Text Input",
    static: true,
    required: true,
    canHaveAnswer: true,
    content: "Last name ",
    canHavePageBreakBefore: true,
    canHaveAlternateForm: true,
    canHaveDisplayHorizontal: true,
    canHaveOptionCorrect: true,
    canHaveOptionValue: true,
    canPopulateFromApi: true,
    field_name: "text_input_80D865BD-831C-4461-B9E2-B67C086DE894",
    label: "Last name ",
    dirty: false,
  },
  {
    id: "BF21BEB0-D680-4C49-8768-21F3521D979A",
    element: "EmailInput",
    text: "Email",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Email Field",
    canHavePageBreakBefore: true,
    canHaveAlternateForm: true,
    canHaveDisplayHorizontal: true,
    canHaveOptionCorrect: true,
    canHaveOptionValue: true,
    canPopulateFromApi: true,
    field_name: "email_input_34E34AE9-EFED-40F4-8A59-153A7427CF34",
    label: "Email",
  },
  {
    id: "E629ECCE-5A83-45B1-ACB4-4749152C8A2B",
    element: "DatePicker",
    text: "Date Field",
    static: false,
    required: false,
    readOnly: false,
    defaultToday: false,
    content: "Birth Date ",
    canHavePageBreakBefore: true,
    canHaveAlternateForm: true,
    canHaveDisplayHorizontal: true,
    canHaveOptionCorrect: true,
    canHaveOptionValue: true,
    canPopulateFromApi: true,
    dateFormat: "MM/dd/yyyy",
    timeFormat: "hh:mm aa",
    showTimeSelect: false,
    showTimeSelectOnly: false,
    showTimeInput: false,
    field_name: "date_picker_41BB3369-14D1-494A-AA8B-7FBB2DA1F57F",
    label: "Birth Date ",
    dirty: false,
  },
  // {
  //   id: "7",
  //   element: "Dropdown",
  //   text: "Dropdown",
  //   static: false,
  //   required: true,
  //   canHaveAnswer: true,
  //   content: "Gender Field",
  //   canHavePageBreakBefore: false,
  //   canHaveAlternateForm: false,
  //   canHaveDisplayHorizontal: false,
  //   canHaveOptionCorrect: false,
  //   canHaveOptionValue: false,
  //   canPopulateFromApi: false,
  //   field_name: "dropdown_53A9ABF6-8E64-472C-B6B2-C1380EDE121D",
  //   label: "Gender",
  //   options: [],
  //   category: "gender",
  // },
  {
    id: "222",
    element: "TextInput",
    text: "Number",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Phone Number Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "phone_number_input_53A9ABF6-8E64-472C-B6B2-C1380EDE343D",
    label: "Phone Number (Primary)",
  },
  // {
  //   id: "311",
  //   element: "TextInput",
  //   text: "Text Input",
  //   static: false,
  //   required: true,
  //   canHaveAnswer: true,
  //   content: "Password Field",
  //   canHavePageBreakBefore: false,
  //   canHaveAlternateForm: false,
  //   canHaveDisplayHorizontal: false,
  //   canHaveOptionCorrect: false,
  //   canHaveOptionValue: false,
  //   canPopulateFromApi: false,
  //   field_name: "password_input_53A9ABF6-8E64-472C-B6B2-C138011343D3",
  //   label: "Password",
  // },
  // {
  //   id: "312",
  //   element: "TextInput",
  //   text: "Text Input",
  //   static: false,
  //   required: true,
  //   canHaveAnswer: true,
  //   content: "Confirm Password Field",
  //   canHavePageBreakBefore: false,
  //   canHaveAlternateForm: false,
  //   canHaveDisplayHorizontal: false,
  //   canHaveOptionCorrect: false,
  //   canHaveOptionValue: false,
  //   canPopulateFromApi: false,
  //   field_name:
  //     "password_confirmation_input_53A9ABF6-8312-472C-B6B2-C138011343D3",
  //   label: "Confirm Password",
  // },
  {
    id: "315",
    element: "Dropdown",
    text: "Dropdown",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Branches Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: true,
    field_name: "api_dropdown_53A9A315-8312-472C-B6B2-C138011343D3",
    label: "Branches",
    options: [],
  },
  {
    id: "1",
    element: "TextInput",
    text: "Text Input",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Street Number Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "street_number_input_53A9A315-8312-472C-B6B2-C13801131213",
    label: "Street #",
  },
  {
    id: "2",
    element: "TextInput",
    text: "Text Input",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Street Name Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "street_name_input_53A9A315-8312-472C-B6B2-C138011RR11",
    label: "Street Name",
  },
  {
    id: "3",
    element: "TextInput",
    text: "Text Input",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Address Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "address_input_53A9A315-8312-472C-B6B2-C138011981D",
    label: "Address",
  },
  {
    id: "4",
    element: "TextInput",
    text: "Text Input",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "City Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "city_input_53A9A315-8312-472C-B6B2-C138011WS32",
    label: "City",
  },
  {
    id: "5",
    element: "Dropdown",
    text: "Dropdown",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "State Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "state_input_53A9A315-8312-472C-B6B2-C138011FR53",
    label: "State",
    options: [],
  },
  {
    id: "6",
    element: "TextInput",
    text: "Text Input",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Zip Code Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "zip_code_input_653A9A315-8312-472C-4444-C138011FR53",
    label: "Zip Code",
  },
  {
    id: "10",
    element: "Dropdown",
    text: "Dropdown",
    static: false,
    required: true,
    canHaveAnswer: true,
    content: "Country Field",
    canHavePageBreakBefore: false,
    canHaveAlternateForm: false,
    canHaveDisplayHorizontal: false,
    canHaveOptionCorrect: false,
    canHaveOptionValue: false,
    canPopulateFromApi: false,
    field_name: "country_input_53ADF315-1111-472C-B6B2-C138011FR53",
    label: "Country",
    options: [],
  },
];
export const customToolbarItems: ToolbarItem[] = [
  // {
  //   key: "Header",
  //   name: "Header",
  //   icon: "fas fa-heading",
  //   static: true,
  //   content: "Header Text",
  // },

  {
    key: "TextInput",
    name: "Text Input",
    icon: "fas fa-font",
    static: false,
    content: "Text Field",
  },
  {
    key: "NumberInput",
    name: "Number",
    icon: "fas fa-hashtag",
    static: false,
    content: "Number Field",
  },
  {
    key: "TextArea",
    name: "Text Area",
    icon: "fas fa-text-height",
    static: false,
    content: "Text Area",
  },
  {
    key: "Dropdown",
    name: "Dropdown",
    icon: "fas fa-caret-square-down",
    static: false,
    content: "Dropdown Field",
  },
  {
    key: "DatePicker",
    name: "Date Field",
    icon: "fas fa-calendar-alt",
    static: false,
    content: "Date Field",
  },
  {
    key: "RadioButtons",
    name: "Radio Group",
    icon: "far fa-dot-circle",
    static: false,
    content: "Radio Group",
  },
  {
    key: "FileUpload",
    name: "File Upload",
    icon: "fas fa-file-upload",
    static: false,
    content: "File Upload",
  },
  {
    key: "EmailInput",
    name: "Email",
    icon: "fas fa-envelope",
    static: false,
    content: "Email Field",
  },
];

export const employeeForm = [
  {
    id: 1,
    name: "Personal Information",
    is_multiple: false,
    key: "personal_info",
    fields: [
      {
        sectionName: "personal_information",
        fields: [
          {
            id: 2,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 1,
            span: "6",
            is_default: true,
            placeholder: "First Name",
            name: "First Name",
            key: "first_name",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "First Name field is required.",
                validation_value: null,
                type: "required",
              },
              {
                message: "Maximum limit for first name is 50.",
                validation_value: "50",
                type: "maxLength",
              },
            ],
          },
          {
            id: 3,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 2,
            span: "6",
            is_default: true,
            placeholder: "Middle Name",
            name: "Middle Name",
            key: "middle_name",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum limit for middle name is 50",
                validation_value: "50",
                type: "maxLength",
              },
            ],
          },
          {
            id: 4,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 3,
            span: "6",
            is_default: true,
            placeholder: "Last Name",
            name: "Last Name",
            key: "last_name",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Last Name field is required.",
                validation_value: null,
                type: "required",
              },
              {
                message: "Maximum limit for last name is 50.",
                validation_value: "50",
                type: "maxLength",
              },
            ],
          },
          // {
          //   id: 7,
          //   type: "select",
          //   category: "gender",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: null,
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 4,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Gender",
          //   name: "Gender",
          //   key: "gender",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Please select gender",
          //       validation_value: null,
          //       type: "required",
          //     },
          //   ],
          // },
          {
            id: 6,
            type: "date",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 5,
            span: "6",
            is_default: true,
            placeholder: "dd/mm/yyyy",
            name: "Birth Date",
            key: "birthdate",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Birth Date field is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
          // {
          //   id: 277,
          //   type: "text",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: null,
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 6,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Social Security Number",
          //   name: "Social Security Number",
          //   key: "social_security_number",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Social Security Number field is required.",
          //       validation_value: "",
          //       type: "required",
          //     },
          //   ],
          // },
          // {
          //   id: 310,
          //   type: "api",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: "/user/role",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 7,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Role(s)",
          //   name: "Role(s)",
          //   key: "type",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Role field is required.",
          //       validation_value: null,
          //       type: "required",
          //     },
          //   ],
          // },
          // {
          //   id: 60,
          //   type: "api",
          //   category: null,
          //   is_disable: false,
          //   is_multiple: true,
          //   url: "/user/services",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 8,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Rank",
          //   name: "Rank",
          //   key: "rank",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Rank field is required.",
          //       validation_value: null,
          //       type: "required",
          //     },
          //   ],
          // },
          // {
          //   id: 275,
          //   type: "select",
          //   category: "ethnicity",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: null,
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 9,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Ethnic Code",
          //   name: "Ethnic Code",
          //   key: "ethnic_code",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [],
          // },
          {
            id: 5,
            type: "email",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 10,
            span: "6",
            is_default: true,
            placeholder: "Email (Primary)",
            name: "Email (Primary)",
            key: "email",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Email (Primary) field is required.",
                validation_value: null,
                type: "required",
              },
              {
                message: "Please enter a valid email.",
                validation_value: null,
                type: "email",
              },
            ],
          },
          {
            id: 278,
            type: "email",
            category: "",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 11,
            span: "6",
            is_default: true,
            placeholder: "Email (Alternate)",
            name: "Email (Alternate)",
            key: "email_address_alternate",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [],
          },
          {
            id: 222,
            type: "phone",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 12,
            span: "6",
            is_default: true,
            placeholder: "Phone Number (Primary)",
            name: "Phone Number (Primary)",
            key: "main_phone",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Phone Number field is required.",
                validation_value: null,
                type: "required",
              },
              {
                message:
                  "Phone Number field must not be greater than 14 characters.",
                validation_value: "14",
                type: "maxLength",
              },
              {
                message: "Phone Number field must be at least 10 characters.",
                validation_value: "10",
                type: "minLength",
              },
            ],
          },
          {
            id: 276,
            type: "phone",
            category: "",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 13,
            span: "6",
            is_default: true,
            placeholder: "Phone Number (Alternate)",
            name: "Phone Number (Alternate)",
            key: "alternate_phone_number",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [],
          },
          {
            id: 30,
            type: "text",
            category: "NULL",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 14,
            span: "6",
            is_default: true,
            placeholder: "Emergency Name",
            name: "Emergency Name",
            key: "emergency_contact_name",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum length for name is 50.",
                validation_value: "50",
                type: null,
              },
            ],
          },
          {
            id: 32,
            type: "phone",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 15,
            span: "6",
            is_default: true,
            placeholder: "Emergency Number",
            name: "Emergency Number",
            key: "emergency_contact_number",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Contact Number field must be at least 10 characters.",
                validation_value: "10",
                type: "minLength",
              },
              {
                message:
                  "Contact Number field must not be greater than 14 characters.",
                validation_value: "14",
                type: "maxLength",
              },
            ],
          },
          {
            id: 33,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 16,
            span: "6",
            is_default: true,
            placeholder: "Emergency Relationship",
            name: "Emergency Relationship",
            key: "emergency_contact_relationship",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [],
          },
          // {
          //   id: 311,
          //   type: "password",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: "",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 17,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Password",
          //   name: "Password",
          //   key: "password",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Password field is required.",
          //       validation_value: null,
          //       type: "required",
          //     },
          //   ],
          // },
          // {
          //   id: 312,
          //   type: "confirm_password",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: "",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 18,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Confirmation Password",
          //   name: "Confirm Password",
          //   key: "confirm_password",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [
          //     {
          //       message: "Confirm Password field is required.",
          //       validation_value: null,
          //       type: "required",
          //     },
          //   ],
          // },
          {
            id: 315,
            type: "text",
            category: "",
            is_disable: false,
            is_multiple: true,
            url: "/company/details",
            options: null,
            group_by: "personal_information",
            sub_group_by: null,
            order_by: 19,
            span: "6",
            is_default: true,
            placeholder: "Branches",
            name: "Branches",
            key: "location_id",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Branch field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          // {
          //   id: 313,
          //   type: "api",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: "guard-tour/site",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 20,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Site",
          //   name: "Site",
          //   key: "client_site",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [],
          // },
          // {
          //   id: 314,
          //   type: "api",
          //   category: "",
          //   is_disable: false,
          //   is_multiple: false,
          //   url: "/template/beats",
          //   options: null,
          //   group_by: "personal_information",
          //   sub_group_by: null,
          //   order_by: 21,
          //   span: "6",
          //   is_default: true,
          //   placeholder: "Beats",
          //   name: "Beats",
          //   key: "beat_id",
          //   selected_check: null,
          //   is_delete: true,
          //   is_view: true,
          //   is_create: true,
          //   is_edit: true,
          //   validations: [],
          // },
          {
            id: 24,
            type: "file_upload",
            category: "file",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "documents",
            sub_group_by: null,
            order_by: 5,
            span: "6",
            is_default: false,
            placeholder: "File Upload",
            name: "File Upload",
            key: "file_upload",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Please upload a file",
                validation_value: null,
                type: "required",
              },
            ],
          },
        ],
      },
      {
        sectionName: "residence_address",
        fields: [
          {
            id: 22,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 1,
            span: "12",
            is_default: true,
            placeholder: "Street #",
            name: "Street #",
            key: "residence_street_address_1",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum limit for street address is 250.",
                validation_value: "250",
                type: "maxLength",
              },
              {
                message: "Street field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 23,
            type: "text",
            category: "NULL",
            is_disable: false,
            is_multiple: false,
            url: "NULL",
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 2,
            span: "12",
            is_default: true,
            placeholder: "Street Name",
            name: "Street Name",
            key: "residence_street_address_2",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Street Name field is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
          {
            id: 320,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 2,
            span: "12",
            is_default: true,
            placeholder: "Ste. Number",
            name: "Ste. Number",
            key: "residence_address",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [],
          },
          {
            id: 24,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 3,
            span: "6",
            is_default: true,
            placeholder: "City",
            name: "City",
            key: "residence_city",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum length for city is 28.",
                validation_value: "28",
                type: "maxLength",
              },
              {
                message: "City field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 25,
            type: "text",
            category: "state",
            is_disable: false,
            is_multiple: false,
            url: "/user/states",
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 4,
            span: "6",
            is_default: true,
            placeholder: "State",
            name: "State",
            key: "residence_state",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "State field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 31,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 5,
            span: "6",
            is_default: true,
            placeholder: "Zip Code",
            name: "Zip Code",
            key: "residence_zip_code",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Zip Code maximum length must be of 6 digit.",
                validation_value: "6",
                type: "maxLength",
              },
              {
                message: "Zip Code field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 309,
            type: "select",
            category: "",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "residence_address",
            sub_group_by: null,
            order_by: 6,
            span: "6",
            is_default: true,
            placeholder: "Country",
            name: "Country",
            key: "residence_country",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Country field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
        ],
      },
      {
        sectionName: "mailing_address",
        fields: [
          {
            id: 26,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 1,
            span: "12",
            is_default: true,
            placeholder: "Street #",
            name: "Street #",
            key: "mailing_street_address_1",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum limit for address is 250.",
                validation_value: "250",
                type: "maxLength",
              },
              {
                message: "Street field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 27,
            type: "text",
            category: "NULL",
            is_disable: false,
            is_multiple: false,
            url: "",
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 2,
            span: "12",
            is_default: true,
            placeholder: "Street Name",
            name: "Street Name",
            key: "mailing_street_address_2",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Street Name field is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
          {
            id: 319,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 2,
            span: "12",
            is_default: true,
            placeholder: "Ste. Number",
            name: "Ste. Number",
            key: "mailing_address",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [],
          },
          {
            id: 28,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 3,
            span: "6",
            is_default: true,
            placeholder: "City",
            name: "City",
            key: "mailing_city",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Maximum limit for city is 28.",
                validation_value: "28",
                type: "maxLength",
              },
              {
                message: "City field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 29,
            type: "text",
            category: "state",
            is_disable: false,
            is_multiple: false,
            url: "/user/states",
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 4,
            span: "6",
            is_default: true,
            placeholder: "State",
            name: "State",
            key: "mailing_state",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "State field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 34,
            type: "text",
            category: null,
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 5,
            span: "6",
            is_default: true,
            placeholder: "Zip Code",
            name: "Zip Code",
            key: "mailing_zip_code",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Zip Code maximum length must be of 6 digit.",
                validation_value: "6",
                type: "maxLength",
              },
              {
                message: "Zip Code field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
          {
            id: 279,
            type: "select",
            category: "",
            is_disable: false,
            is_multiple: false,
            url: null,
            options: null,
            group_by: "mailing_address",
            sub_group_by: null,
            order_by: 6,
            span: "6",
            is_default: true,
            placeholder: "Country",
            name: "Country",
            key: "mailing_country",
            selected_check: null,
            is_delete: true,
            is_view: true,
            is_create: true,
            is_edit: true,
            validations: [
              {
                message: "Country field is required.",
                validation_value: "",
                type: "required",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Permits",
    is_multiple: false,
    key: "guard_information",
    fields: [
      {
        id: 13,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/19",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "Driver License",
        name: "Driver License",
        key: "driver_license",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 200,
            type: "text",
            group_by: null,
            category: "state",
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: "/user/states",
            options: null,
            is_default: true,
            placeholder: "State",
            name: "State",
            key: "state",
            validations: [
              // {
              //   message: "State field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
            ],
          },
          {
            id: 201,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Driver's License Number",
            name: "Driver's License Number",
            key: "permit_number",
            validations: [
              {
                message: "Please enter valid License number.",
                validation_value: "^[A-Z](?:\\d[- ]*){14}$",
                type: "pattern",
              },
              {
                message: "Maximum limit For  driving license number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              // {
              //   message: "Driver's License Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
            ],
          },
          {
            id: 202,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 203,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 204,
            type: "textarea",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Notes",
            name: "Notes",
            key: "note",
            validations: [
              {
                message: "Maximum limit for note is 250.",
                validation_value: "250",
                type: "maxLength",
              },
            ],
          },
          {
            id: 260,
            type: "file",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Upload",
            name: "Upload",
            key: "file",
            // validations: [
            //   {
            //     message: "The upload resume/cv field is required..",
            //     validation_value: null,
            //     required: true
            //   },
            // ],
          },
        ],
      },
      {
        id: 14,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/20",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "Guard Card",
        name: "Guard Card",
        key: "guard_card",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 205,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              {
                message: "Please enter valid permit number.",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
            ],
          },
          {
            id: 206,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 265,
            type: "file",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Upload",
            name: "Upload",
            key: "file",
            validations: [
              {
                message: "File is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
          {
            id: 317,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
        ],
      },
      {
        id: 15,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/21",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "Firearms Qualification",
        name: "Firearms Qualification",
        key: "firearms",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 209,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
              {
                message: "Please enter valid permit number.",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
            ],
          },
          {
            id: 210,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 211,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 321,
            type: "text",
            group_by: "firearms",
            category: null,
            is_disable: false,
            span: "5",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Caliber",
            name: "Caliber",
            key: "caliber",
            validations: [
              {
                message: "Maximum limit for Caliber is 100.",
                validation_value: "100",
                type: "maxLength",
              },
            ],
          },
          {
            id: 322,
            type: "text",
            group_by: "firearms",
            category: null,
            is_disable: false,
            span: "5",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Serial #",
            name: "Serial #",
            key: "serial",
            validations: [
              {
                message: "Maximum limit for Serial # is 100. ",
                validation_value: "100",
                type: "maxLength",
              },
            ],
          },
          {
            id: 323,
            type: "text",
            group_by: "firearms",
            category: null,
            is_disable: false,
            span: "5",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Make",
            name: "Make",
            key: "make",
            validations: [
              {
                message: "Maximum limit for Make is 100.",
                validation_value: "100",
                type: "maxLength",
              },
            ],
          },
          {
            id: 324,
            type: "text",
            group_by: "firearms",
            category: null,
            is_disable: false,
            span: "5",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Model",
            name: "Model",
            key: "model",
            validations: [
              {
                message: "Maximum limit for Model is 100. ",
                validation_value: "100",
                type: "maxLength",
              },
            ],
          },
        ],
      },
      {
        id: 16,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/22",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "Baton ",
        name: "Baton ",
        key: "baton",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 213,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
              {
                message: "Please enter valid permit number",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
            ],
          },
          {
            id: 214,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 215,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 216,
            type: "textarea",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Notes",
            name: "Notes",
            key: "note",
            validations: [
              {
                message: "Maximum limit for note is 250.",
                validation_value: "250",
                type: "maxLength",
              },
            ],
          },
          {
            id: 271,
            type: "file",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Upload",
            name: "Upload",
            key: "file",
            validations: [
              {
                message: "File is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
        ],
      },
      {
        id: 17,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/25",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "ECD ",
        name: "ECD ",
        key: "ecd",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 236,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
              {
                message: "Please enter valid permit number",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
            ],
          },
          {
            id: 237,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 238,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 239,
            type: "textarea",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Notes",
            name: "Notes",
            key: "note",
            validations: [
              {
                message: "Maximum limit for note is 250.",
                validation_value: "252",
                type: "maxLength",
              },
            ],
          },
        ],
      },
      {
        id: 18,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/23",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "OC Spray",
        name: "OC Spray",
        key: "oc",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 217,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
              {
                message: "Please enter valid permit number",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
            ],
          },
          {
            id: 218,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 219,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 220,
            type: "textarea",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Notes",
            name: "Notes",
            key: "note",
            validations: [
              {
                message: "Maximum limit for note is 250.",
                validation_value: "250",
                type: "maxLength",
              },
            ],
          },
        ],
      },
      {
        id: 19,
        type: "button",
        category: null,
        is_disable: false,
        is_multiple: false,
        url: "user/employee-form/31",
        options: null,
        group_by: null,
        sub_group_by: null,
        order_by: null,
        span: "12",
        is_default: true,
        placeholder: "Other Permit",
        name: "Other Permit",
        key: "other_permit",
        selected_check: null,
        is_delete: true,
        is_view: true,
        is_create: true,
        is_edit: true,
        validations: [],
        fields: [
          {
            id: 291,
            type: "text",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Permit Number",
            name: "Permit Number",
            key: "permit_number",
            validations: [
              {
                message: "Please enter valid permit number",
                validation_value: " /^[0-9]+$/",
                type: "pattern",
              },
              // {
              //   message: "Permit Number field is required.",
              //   validation_value: null,
              //   type: "required",
              // },
              {
                message: "Maximum limit for permit number is 14.",
                validation_value: "14",
                type: "maxLength",
              },
            ],
          },
          {
            id: 292,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Issue",
            name: "Date of Issue",
            key: "date_of_issue",
            validations: [],
          },
          {
            id: 293,
            type: "date",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Date of Expiration",
            name: "Date of Expiration",
            key: "date_of_expiry",
            validations: [],
          },
          {
            id: 294,
            type: "textarea",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Notes",
            name: "Notes",
            key: "notes",
            validations: [
              {
                message: "Maximum limit for description is 250.",
                validation_value: "250",
                type: "maxLength",
              },
            ],
          },
          {
            id: 295,
            type: "file",
            group_by: null,
            category: null,
            is_disable: false,
            span: "12",
            is_multiple: false,
            url: null,
            options: null,
            is_default: true,
            placeholder: "Upload",
            name: "Upload",
            key: "file",
            validations: [
              {
                message: "File is required.",
                validation_value: null,
                type: "required",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 10,
    name: "Available Times",
    is_multiple: false,
    key: "available_time",
    fields: [],
  },
  // {
  //   id: 7,
  //   name: "References",
  //   is_multiple: false,
  //   key: "references",
  //   fields: [
  //     {
  //       id: 244,
  //       type: "text",
  //       group_by: null,
  //       category: null,
  //       is_disable: false,
  //       span: "12",
  //       is_multiple: false,
  //       url: null,
  //       options: null,
  //       is_default: true,
  //       placeholder: "Reference Type",
  //       name: "Reference Type",
  //       key: "reference_type",
  //       validations: [
  //         {
  //           message: "Maximum limit for Reference Type is 100.",
  //           validation_value: "100",
  //           type: "maxLength",
  //         },
  //         // {
  //         //   message: "Reference Type field is required",
  //         //   validation_value: null,
  //         //   type: "required",
  //         // },
  //       ],
  //     },
  //     {
  //       id: 245,
  //       type: "text",
  //       group_by: null,
  //       category: null,
  //       is_disable: false,
  //       span: "12",
  //       is_multiple: false,
  //       url: null,
  //       options: null,
  //       is_default: true,
  //       placeholder: "Date of Issue",
  //       name: "Reference Value",
  //       key: "refrence_value",
  //       validations: [
  //         // {
  //         //   message: "Reference Value field is required",
  //         //   validation_value: null,
  //         //   type: "required",
  //         // },
  //         {
  //           message: "Maximum limit for Reference Value is 100.",
  //           validation_value: "100",
  //           type: "maxLength",
  //         },
  //       ],
  //     },

  //   ],
  // },
  {
    "id": 7,
    "name": "References",
    "is_multiple": false,
    "key": "references",
    "fields": [
      {
        "id": 246,
        "type": "text",
        "group_by": null,
        "category": null,
        "is_disable": false,
        "span": "12",
        "is_multiple": false,
        "url": null,
        "options": null,
        "is_default": true,
        "placeholder": "Person Name",
        "name": "Person Name",
        "key": "reference_name",
        "validations": [
          {
            "message": "Person Name is required.",
            "validation_value": null,
          }
        ]
      },
      {
        "id": 247,
        "type": "text",
        "group_by": null,
        "category": null,
        "is_disable": false,
        "span": "12",
        "is_multiple": false,
        "url": null,
        "options": null,
        "is_default": true,
        "placeholder": "Relationship",
        "name": "Relationship",
        "key": "reference_relationship",
        "validations": [
          {
            "message": "Relationship is required.",
            "validation_value": null,
          }
        ]
      },
      {
        "id": 250,
        "type": "text",
        "group_by": null,
        "category": null,
        "is_disable": false,
        "span": "12",
        "is_multiple": false,
        "url": null,
        "options": null,
        "is_default": true,
        "placeholder": "Title",
        "name": "Title",
        "key": "reference_title",
        "validations": [
          {
            "message": "Title is required.",
            "validation_value": null,
          }
        ]
      },

      {
        "id": 248,
        "type": "text",
        "group_by": null,
        "category": null,
        "is_disable": false,
        "span": "12",
        "is_multiple": false,
        "url": null,
        "options": null,
        "is_default": true,
        "placeholder": "Phone#",
        "name": "Phone#",
        "key": "reference_phone",
        "validations": [
          {
            "message": "Please enter a valid 10-digit phone number.",
            "validation_value": "^[0-9]{10}$",
            "type": "pattern"
          }
        ]
      },
      {
        "id": 249,
        "type": "text",
        "group_by": null,
        "category": null,
        "is_disable": false,
        "span": "12",
        "is_multiple": false,
        "url": null,
        "options": null,
        "is_default": true,
        "placeholder": "Email",
        "name": "Email",
        "key": "reference_email",
        "validations": [
          {
            "message": "Please enter a valid email address.",
            "validation_value": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
            "type": "pattern"
          }
        ]
      },

    ]
  }
  
];
